### PR TITLE
Use collections.abc

### PR DESCRIPTION
**Pull request by srittau**
Based on feedback from typing-sig

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Do we know if all type checkers already support this?

**Comment by srittau** [comment]
Since all type checkers claim to support built-in generics (minus bugs), we now use `collections.abc` in a few places in typeshed, and the tests pass, I'd say it is safe enough.

**Review by JelleZijlstra — APPROVED** [review]
Sounds good.

CI is apparently failing due to an issue with the PEP headers.

**Comment by srittau** [comment]
I'll look into the headers when submitting the PEP to the pep repository.

**Pull request merged**
